ventas = [
    {"producto": "Laptop", "precio": 1200, "cantidad": 3, "categoria": "Tecnología", "sucursal": "Norte"},
    {"producto": "Mouse", "precio": 25, "cantidad": 12, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Teclado", "precio": 45, "cantidad": 8, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Monitor", "precio": 220, "cantidad": 5, "categoria": "Tecnología", "sucursal": "Norte"},
    {"producto": "Impresora", "precio": 150, "cantidad": 4, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Silla", "precio": 140, "cantidad": 7, "categoria": "Muebles", "sucursal": "Norte"},
    {"producto": "Escritorio", "precio": 300, "cantidad": 3, "categoria": "Muebles", "sucursal": "Sur"},
    {"producto": "Lámpara", "precio": 35, "cantidad": 10, "categoria": "Hogar", "sucursal": "Sur"},
    {"producto": "Cafetera", "precio": 60, "cantidad": 6, "categoria": "Hogar", "sucursal": "Centro"},
    {"producto": "Ventilador", "precio": 55, "cantidad": 9, "categoria": "Hogar", "sucursal": "Norte"},
    {"producto": "Bocinas", "precio": 80, "cantidad": 7, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Tablet", "precio": 300, "cantidad": 4, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Smartphone", "precio": 900, "cantidad": 5, "categoria": "Tecnología", "sucursal": "Norte"},
    {"producto": "Cargador", "precio": 20, "cantidad": 18, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Cable HDMI", "precio": 12, "cantidad": 25, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Alfombra", "precio": 70, "cantidad": 3, "categoria": "Hogar", "sucursal": "Centro"},
    {"producto": "Cuadro Decorativo", "precio": 40, "cantidad": 5, "categoria": "Hogar", "sucursal": "Norte"},
    {"producto": "Sofá", "precio": 800, "cantidad": 2, "categoria": "Muebles", "sucursal": "Centro"},
    {"producto": "Estante", "precio": 150, "cantidad": 3, "categoria": "Muebles", "sucursal": "Sur"},
    {"producto": "Cama", "precio": 600, "cantidad": 1, "categoria": "Muebles", "sucursal": "Norte"},
    {"producto": "Audífonos", "precio": 50, "cantidad": 14, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Batería Portátil", "precio": 35, "cantidad": 13, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Reloj Inteligente", "precio": 180, "cantidad": 5, "categoria": "Tecnología", "sucursal": "Norte"},
    {"producto": "Router", "precio": 90, "cantidad": 4, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Horno", "precio": 200, "cantidad": 2, "categoria": "Hogar", "sucursal": "Centro"},
    {"producto": "Tostador", "precio": 45, "cantidad": 6, "categoria": "Hogar", "sucursal": "Centro"},
    {"producto": "Sábanas", "precio": 30, "cantidad": 8, "categoria": "Hogar", "sucursal": "Sur"},
    {"producto": "Colchón", "precio": 500, "cantidad": 1, "categoria": "Muebles", "sucursal": "Norte"},
    {"producto": "Mesa de Noche", "precio": 120, "cantidad": 3, "categoria": "Muebles", "sucursal": "Centro"},
    {"producto": "Organizador", "precio": 25, "cantidad": 12, "categoria": "Hogar", "sucursal": "Norte"},
    {"producto": "Calculadora", "precio": 15, "cantidad": 20, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Teclado Mecánico", "precio": 90, "cantidad": 7, "categoria": "Tecnología", "sucursal": "Norte"},
    {"producto": "Monitor 4K", "precio": 400, "cantidad": 3, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Silla Gamer", "precio": 250, "cantidad": 4, "categoria": "Muebles", "sucursal": "Centro"},
    {"producto": "Hervidor", "precio": 30, "cantidad": 9, "categoria": "Hogar", "sucursal": "Sur"},
    {"producto": "Microondas", "precio": 120, "cantidad": 3, "categoria": "Hogar", "sucursal": "Norte"},
    {"producto": "Air Fryer", "precio": 150, "cantidad": 5, "categoria": "Hogar", "sucursal": "Centro"},
    {"producto": "Camara Web", "precio": 70, "cantidad": 8, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Tripie", "precio": 30, "cantidad": 10, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Cajonera", "precio": 180, "cantidad": 2, "categoria": "Muebles", "sucursal": "Norte"},
    {"producto": "Perchero", "precio": 40, "cantidad": 6, "categoria": "Hogar", "sucursal": "Sur"},
    {"producto": "Cojines", "precio": 25, "cantidad": 10, "categoria": "Hogar", "sucursal": "Centro"},
    {"producto": "Escoba Eléctrica", "precio": 90, "cantidad": 4, "categoria": "Hogar", "sucursal": "Norte"},
    {"producto": "Cámara DSLR", "precio": 850, "cantidad": 2, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Memoria USB", "precio": 12, "cantidad": 30, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Disco Duro", "precio": 70, "cantidad": 6, "categoria": "Tecnología", "sucursal": "Norte"},
    {"producto": "SSD", "precio": 110, "cantidad": 5, "categoria": "Tecnología", "sucursal": "Sur"},
    {"producto": "Soporte Monitor", "precio": 35, "cantidad": 7, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Silla Oficina", "precio": 160, "cantidad": 4, "categoria": "Muebles", "sucursal": "Sur"},
    {"producto": "Repisa", "precio": 55, "cantidad": 6, "categoria": "Muebles", "sucursal": "Norte"},
    {"producto": "Hielera", "precio": 40, "cantidad": 5, "categoria": "Hogar", "sucursal": "Centro"},
    {"producto": "Filtro de Agua", "precio": 65, "cantidad": 7, "categoria": "Hogar", "sucursal": "Sur"},
    {"producto": "Plancha", "precio": 35, "cantidad": 9, "categoria": "Hogar", "sucursal": "Norte"},
    {"producto": "Cámara Deportiva", "precio": 120, "cantidad": 4, "categoria": "Tecnología", "sucursal": "Centro"},
    {"producto": "Audífonos Pro", "precio": 150, "cantidad": 6, "categoria": "Tecnología", "sucursal": "Norte"},
    {"producto": "Luces LED", "precio": 25, "cantidad": 15, "categoria": "Hogar", "sucursal": "Sur"},
    {"producto": "Switch HDMI", "precio": 20, "cantidad": 16, "categoria": "Tecnología", "sucursal": "Centro"},
]